# sops-nix configuration
# See: https://github.com/Mic92/sops-nix
#
# This file configures which keys can encrypt/decrypt which secrets.
# Uses Yubikey-backed age keys via age-plugin-yubikey.
#
# To set up a new Yubikey:
# 1. Run the setup wizard:
#    age-plugin-yubikey
#
# 2. Save the identity file:
#    age-plugin-yubikey --identity > ~/.config/sops/age/yubikey-identity.txt
#    chmod 600 ~/.config/sops/age/yubikey-identity.txt
#
# 3. Get your public key:
#    age-plugin-yubikey --list
#
# 4. Add the public key below under 'keys'
#
# 5. Create/edit secrets (requires Yubikey touch):
#    cd ~/Projects/dotfiles/secrets
#    SOPS_AGE_KEY_FILE=~/.config/sops/age/yubikey-identity.txt sops secrets.yaml

keys:
  # John's Yubikey 5C NFC (primary)
  # Yubikey-backed age key - private key never leaves hardware
  - &john age1yubikey1qghhvxsh9ttxpqvnf3um7fuv7y0ut4hvl5gk2rgwtezj0e2avkmd7chvckq

  # Future: Backup Yubikey
  # - &john-backup age1yubikey1q...

  # Future: Host-specific keys (for per-host secrets)
  # - &mac-studio age1...

# Creation rules define which keys can access which files
creation_rules:
  # Default rule: all secrets encrypted to john's Yubikey
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *john

  # Future: Host-specific secrets
  # - path_regex: mac-studio\.yaml$
  #   key_groups:
  #     - age:
  #         - *john
  #         - *mac-studio
